name: lama-lab
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - black
  - dill
  - ipykernel
  - ipympl
  - ipywidgets
  - matplotlib
  - numpy
  - pytest
  - pytorch
  - scipy>=1.18.0
  - pip