agent:
  decay_delta: 0.20
  decay_eta: 0.75
  delta_0: 0.5
  eta_0: 0.05
  init_x:
  - 0.0
  - 1.0
  max_grad_norm: 5.0
  min_delta: 0.001
  min_eta: 0.001
  type: AgentPZOMD
env:
  epsilon: 0.001
  n_episodes: 10
  n_makers: 2
  n_rounds: 50000
experiment_name: pzomd_low_decay_1fp
generator:
  high: 1.0
  low: 0.0
  means:
  - 0.15
  - 0.5
  - 0.85
  stds:
  - 0.03
  - 0.1
  - 0.03
  type: GaussianMixtureGenerator
  weights:
  - 0.0
  - 1.0
  - 0.0
history_window: 1
n_samples: 1000000
projector:
  epsilon: 0.001
  high: 1.0
  low: 0.0
  type: MarketMakingProjector